import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const defaultLanguage = 'English';

const languageOptions = [
  { key: 'English', label: 'English' },
  { key: 'Japanese', label: '日本語' },
];

const translations = {
  English: {
    appName: 'WorkPulse',
    appTagline: 'Enterprise work orchestration',
    holidays: {
      newYear: 'New Year’s Day',
      comingOfAge: 'Coming of Age Day',
      nationalFoundation: 'National Foundation Day',
      emperorsBirthday: 'Emperor’s Birthday',
      vernalEquinox: 'Vernal Equinox Day',
      showa: 'Shōwa Day',
      constitutionMemorial: 'Constitution Memorial Day',
      greenery: 'Greenery Day',
      children: 'Children’s Day',
      marine: 'Marine Day',
      mountain: 'Mountain Day',
      respectForTheAged: 'Respect for the Aged Day',
      autumnalEquinox: 'Autumnal Equinox Day',
      sports: 'Sports Day',
      culture: 'Culture Day',
      laborThanksgiving: 'Labor Thanksgiving Day',
    },
    header: {
      workspace: 'Workspace',
      navigationHub: 'Navigation hub',
      quickStats: {
        hours: 'Hours',
        meetings: 'Meetings',
        tasks: 'Tasks',
      },
    },
    nav: {
      dashboard: 'Dashboard',
      planner: 'Worklog-Planning',
      worklog: 'Worklog-Approving',
      calendar: 'Calendar',
      timesheet: 'Timesheet',
      reports: 'Reports',
      notifications: 'Notifications',
      projects: 'Projects',
      meetings: 'Meetings',
    },
    menu: {
      profile: 'Profile',
      settings: 'Settings',
      worklogs: 'My Worklogs',
      reports: 'Reports',
      notifications: 'Notifications',
      signOut: 'Sign out',
    },
    settings: {
      settingsLabel: 'Settings',
      pageTitle: 'Application preferences',
      pageDescription: 'Manage your language, theme mode, and the live color palette.',
      languageTitle: 'Language',
      languageDescription: 'Choose the display language for the application UI.',
      themeTitle: 'Theme mode',
      themeDescription: 'Switch between light and dark modes.',
      lightMode: 'Light mode',
      darkMode: 'Dark mode',
      themeColorsTitle: 'Theme colors',
      themeColorsDescription: 'Adjust the live color palette for the current mode.',
      resetTheme: 'Restore default theme',
      resetThemeDescription: 'Revert the theme back to the original default palette.',
      colors: {
        accent: { label: 'Accent', description: 'Primary actions and highlights' },
        background: { label: 'Background', description: 'Page surface color' },
        surface: { label: 'Surface', description: 'Cards and panels' },
        textPrimary: { label: 'Text', description: 'Primary typography' },
        textSecondary: { label: 'Secondary text', description: 'Muted labels and helpers' },
      },
    },
    account: {
      profileCompletion: 'Profile completion',
    },
    notFound: {
      message: 'Page not found. Please use the navigation menu.',
    },
    common: {
      save: 'Save',
      saving: 'Saving...',
      cancel: 'Cancel',
      edit: 'Edit',
      backToLogin: 'Back to login',
      createAccount: 'Create account',
      tryRecoveryAgain: 'Try recovery again',
      loading: 'Loading...',
      completeProfile: 'Complete profile',
      signOut: 'Sign out',
      tbd: 'TBD',
      statuses: {
        planned: 'Planned',
        inProgress: 'In progress',
        submitted: 'Submitted',
        approved: 'Approved',
        rejected: 'Rejected',
        completed: 'Completed',
        cancelled: 'Cancelled',
        onTrack: 'On track',
      },
    },
    auth: {
      loginTitle: 'Secure login',
      loginSubtitle: 'Access your daily work planner and analytics dashboard.',
      employeeId: 'Employee ID',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loginButton: 'Login',
      noAccount: 'Don’t have an account?',
      registerLink: 'Register',
      registerTitle: 'Create your account',
      registerSubtitle: 'Set up your employee profile and join the team.',
      fullName: 'Full Name',
      companyEmail: 'Company Email',
      department: 'Department',
      confirmPassword: 'Confirm Password',
      createAccountButton: 'Create account',
      alreadyHaveAccount: 'Already have an account?',
      loginLink: 'Login',
      passwordMinLength: 'Password must be at least 8 characters long.',
      passwordsMustMatch: 'Passwords must match.',
      registrationFailed: 'Registration failed. Please try again.',
      loginFailed: 'Login failed. Please verify your credentials.',
      sessionExpired: 'Your session expired, so recent changes may not have been saved. Sign in again to continue.',
      placeholders: {
        fullName: 'Jane Doe',
        email: 'name@company.com',
        employeeId: 'EMP-001',
        department: 'Engineering',
      },
    },
    recovery: {
      title: 'Forgot password',
      subtitle: 'Answer security questions to reset your password without email verification.',
      recoverTitle: 'Recover your account',
      recoverSubtitle: 'Answer security questions to reset your password without email verification.',
      companyEmail: 'Company Email',
      employeeId: 'Employee ID',
      selectQuestions: 'Select exactly 3 questions from the list below, then answer them.',
      answerPlaceholder: 'Your answer',
      verifyAnswers: 'Verify answers',
      startRecovery: 'Start recovery',
      backToLogin: 'Back to login',
      createAccount: 'Create account',
      errors: {
        missingIdentity: 'Please enter both Employee ID and company email.',
        selectThree: 'Select exactly 3 questions and answer them to continue.',
        exactlyThree: 'Please select exactly 3 security questions.',
        answerAll: 'Please answer all selected security questions.',
      },
    },
    resetPassword: {
      title: 'Reset password',
      subtitle: 'Use the recovery token to choose a secure new password.',
      heading: 'Set a new password',
      newPassword: 'New password',
      confirmPassword: 'Confirm new password',
      resetButton: 'Reset password',
      success: 'Password reset successfully. Redirecting to login...',
      emptyFields: 'Please fill both password fields.',
      passwordMinLength: 'Password must be at least 8 characters long.',
      passwordsMustMatch: 'Passwords must match.',
      backToLogin: 'Back to login',
      tryRecoveryAgain: 'Try recovery again',
    },
    security: {
      title: 'Set up your security questions',
      subtitle: 'Answer these questions now so you can recover your account later without email verification.',
      loading: 'Loading your security questions...',
      answerPlaceholder: 'Type your answer',
      saveButton: 'Save my answers',
      saving: 'Saving...',
      answerAll: 'Please answer all security questions.',
      saved: 'Your security questions have been saved.',
    },
    dashboard: {
      badge: 'WorkPulse Command Center',
      title: 'Worklog dashboard',
      description: 'Track average output, task health, and workload balance at a glance with live, theme-aware analytics.',
      filters: {
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
      },
      overview: {
        totalWorkHours: 'Total work hours',
        totalWorkHoursDescription: 'Steady focus this period',
        completedTasks: 'Completed tasks',
        completedTasksDescription: 'Across filtered worklogs',
        pendingTasks: 'Pending tasks',
        pendingTasksDescription: 'Needs follow-up',
        inProgress: 'In progress',
        inProgressDescription: 'Currently active tasks',
        overdue: 'Overdue',
        overdueDescription: 'Blocked or stuck items',
      },
      sections: {
        workHours: 'Work hours & productivity',
        workHoursDescription: 'A clearer view of delivery velocity over the selected period.',
        productivity: 'Productivity',
        workHoursCard: 'Work hours',
        taskCompletion: 'Task completion',
        liveRange: 'Live range',
        loading: 'Loading',
        completionTrend: 'Completion trend',
        taskHistory: 'Task history',
        estimatedTime: 'Estimated time',
      },
      workHoursTrend: '{delta} vs previous {period}',
      workHoursTrendNone: 'No comparison data',
      periods: {
        daily: 'day',
        weekly: 'week',
        monthly: 'month',
      },
      pendingTasksTitle: 'Pending tasks',
      pendingTasksDescription: 'The next actions that need attention this period.',
      pendingTasksActive: 'active',
      pendingTasksNone: 'No pending tasks',
      pendingTaskDueLabel: 'Due',
      pendingTaskPriorityLabel: 'Priority',
      pendingTaskEstimateLabel: 'Estimate',
      pendingTasksEmptyDescription: 'You have a clear runway today.',
      insightsTitle: 'Insights & recommendations',
      insightsDescription: 'A digest of trends and what to focus on next.',
      insightsAction: 'Auto-synced',
      insights: {
        completionRateDescription: 'Completion rate based on filtered tasks.',
        taskHistoryDescription: 'Total tasks in the current workspace.',
        estimatedTimeDescription: 'Expected working hours for the date range.',
      },
      error: 'Unable to load dashboard data.',
      emptyRange: 'No time has been logged in this {period} period yet. Switch the period above, or record actuals on the Worklog-Approving page.',
    },
    planner: {
      pageTitle: 'Daily work planner',
      pageDescription: 'Select a date, fill morning tasks and meetings, then save your plan.',
      selectedWeek: 'Selected week',
      weeklyCalendarLabel: 'Weekly calendar',
      selectedDate: 'Selected date',
      holidayWeekend: 'Holiday / weekend',
      currentDate: 'Current date',
      tapADay: 'Tap a day',
      messages: {
        holidayNotice: 'No saved plan for {holiday}. Start planning for this date.',
        noSavedWorklog: 'No planner data saved for this date yet.',
        savedWorklogLoaded: 'Saved worklog loaded for this date.',
      },
      morningPlannerTitle: 'Morning planner',
      morningPlannerDescription: 'Enter your morning tasks and meetings, then preview and save your schedule.',
      previewButton: 'Preview',
      saveButton: 'Save plan',
      documentation: 'Documentation',
      others: 'Others',
      plannedMinutes: 'Planned minutes',
      description: 'Description',
      totalPlannedTime: 'Total planned time',
      goal: 'Goal: 8h',
      readyToSave: 'Ready to save',
      needMore: 'Need {remaining} more',
      previewTitle: 'Preview',
      previewDescription: 'Review your task and meeting details before saving.',
      draft: 'Draft',
      totalPlanned: 'Total planned',
      tasksPreview: 'Tasks preview',
      meetingsPreview: 'Meetings preview',
      taskSectionTitle: 'Task planning',
      taskSectionDescription: 'Organize work items, planned minutes, and task status for the day.',
      addTask: 'Add task',
      taskNameLabel: 'Task name',
      projectLabel: 'Project',
      taskDescriptionLabel: 'Task description',
      taskStatusLabel: 'Status',
      meetingSectionTitle: 'Meeting planning',
      meetingSectionDescription: 'Schedule meetings and keep notes for each discussion.',
      addMeeting: 'Add meeting',
      meetingLabel: 'Meeting',
      meetingScheduledDescription: 'Scheduled meeting details',
      meetingTitleLabel: 'Meeting title',
      meetingFromLabel: 'From',
      meetingToLabel: 'To',
      meetingDescriptionLabel: 'Description',
      meetingTypeLabel: 'Meeting type',
      meetingTypes: {
        meeting: 'Meeting',
        call: 'Call',
        review: 'Review',
      },
      durationLabel: 'Duration',
      minutesLabel: 'min',
      planned: 'Planned',
      noDocumentationNotes: 'No documentation notes added.',
      noOtherNotes: 'No other notes added.',
      untitledTask: 'Untitled task',
      noProject: 'No project',
      loadingProjects: 'Loading projects…',
      noProjectsYet: 'No projects registered yet. Add one on the Projects page.',
      noProjectSelected: 'No project selected',
      noDescriptionAdded: 'No description added.',
      untitledMeeting: 'Untitled meeting',
      noTimeSelected: 'No time selected',
      validation: {
        eachTaskNeedsTitle: 'Each task needs a title.',
        minutesCannotBeNegative: 'Planned minutes cannot be negative.',
        exceeds24Hours: 'Daily plan exceeds 24 hours.',
        meetingTitleEmpty: 'Meeting titles cannot be empty.',
        resolveBeforeSaving: 'Please resolve the planner validation issues before saving.',
        previewBeforeSaving: 'Please preview your planner before saving.',
        need8Hours: 'You need at least 8 hours of planned time before saving.',
        savedSuccess: 'Planning saved successfully. You can edit it again by selecting the date.',
        previewReady: 'Preview ready. Review the schedule below, then click Save planning to persist it.',
        autosaved: 'Draft autosaved.',
        saveFailed: 'Could not save the plan to the server. Check your connection and try again.',
        autosaveFailed: 'Autosave could not reach the server. Your changes are kept locally for now.',
        resolveBeforePreview: 'Please resolve the planner validation issues before previewing.',
      },
      placeholders: {
        minutes: 'Minutes',
        taskName: 'Task name',
        projectName: 'Project name',
        taskDescription: 'Task description',
        meetingName: 'Meeting name',
        meetingDescription: 'Meeting description',
        notesForDocumentation: 'Notes for documentation work',
        notesForOtherActivities: 'Notes for other activities',
      },
      eightHoursReached: '8 hours planned',
    },
    worklog: {
      eyebrow: 'Daily execution',
      detailTypes: {
        task: 'Task',
        meeting: 'Meeting',
        documentation: 'Documentation',
        other: 'Other',
      },
      taskFallback: 'Task {index}',
      meetingFallback: 'Meeting {index}',
      othersTitle: 'Others',
      plannedMinutesBadge: 'Planned {minutes} min',
      pageTitle: 'Worklog execution',
      pageDescription: 'Use the calendar to open a planned day, review the planned items, and update the actual execution details when you are ready.',
      weeklyCalendar: 'Weekly calendar',
      chooseAnyDay: 'Choose any day to edit that worklog',
      plannedDay: 'Planned day',
      plannedDayDescription: 'The planner data for this date is shown below. Edit mode unlocks the actual-time fields.',
      editExecution: 'Edit execution',
      cancelEdit: 'Cancel edit',
      noPlanner: 'No planner exists for this date yet, but you can still record the actual execution details and save them here.',
      plannedVsActual: 'Planned vs actual',
      overview: 'Daily execution overview',
      extraTime: 'Extra time',
      lessTime: 'Less time',
      onTarget: 'On target',
      planned: 'Planned',
      actual: 'Actual',
      plannedItems: 'Planned items and actual effort',
      actualMinutes: 'Actual minutes spent',
      notes: 'Notes',
      noNotesYet: 'No notes yet.',
      statusSummary: 'Status summary',
      currentState: 'Current state',
      difference: 'Difference',
      review: 'Review',
      reviewDescription: 'The plan stays intact, and only the actual execution details are updated when you choose to edit.',
      saveWorklog: 'Save worklog',
      saveSuccess: 'Worklog saved successfully.',
      saveFailed: 'Could not save the worklog to the server. Check your connection and try again.',
      loadFailed: 'Could not load this day from the server. Check your connection and try again.',
      sessionStatus: 'Session status',
      sessionStatuses: {
        pendingToStart: 'Pending to start',
        ongoing: 'Ongoing',
        completed: 'Completed',
      },
      minutes: 'min',
    },
    timesheet: {
      pageTitle: 'Worklog time summary & task hours',
      pageDescription: 'Review worklog-driven productivity, task-level hours, and overtime without creating separate time-tracking records.',
      anchorDate: 'Anchor date',
      loading: 'Loading your worklog analytics…',
      emptyTitle: 'No worklog data has been saved yet.',
      emptyDescription: 'Save a worklog from the daily worklog experience to populate this analytics module.',
      totalLogged: 'Total logged',
      totalLoggedSubtitle: 'Across all saved worklog records',
      dailyHours: 'Daily hours',
      weeklyHours: 'Weekly hours',
      monthlyHours: 'Monthly hours',
      remainingRequired: 'Remaining required',
      completedTasks: 'Completed tasks',
      taskLevelHours: 'Task-level hours',
      breakdownTitle: 'Task and project breakdown',
      entries: '{count} entries',
      timeDistribution: 'Time distribution',
      projectHours: 'Project hours',
      worklogHistory: 'Worklog history',
      filterAndReview: 'Filter and review worklog entries',
      filtersEnabled: 'Filters enabled',
      startDate: 'Start date',
      endDate: 'End date',
      project: 'Project',
      task: 'Task',
      status: 'Status',
      allProjects: 'All projects',
      allTasks: 'All tasks',
      allStatuses: 'All statuses',
      emptyFilters: 'No worklog entries match the selected filters.',
      groupingLabel: 'Show as',
      groupByTask: 'One row per task',
      groupByDate: 'One row per day',
      matchLabel: 'Merge names',
      matchModes: {
        exact: 'Exact name only',
        similar: 'Similar names',
        loose: 'Loosely related',
      },
      matchHint: {
        exact: 'Only entries written with exactly the same title are combined.',
        similar: 'Rewordings of the same task are combined — "BBox overlay and debug screen" joins "BBox and debug screen Implementation".',
        loose: 'Anything sharing most of its wording is combined, so related work lands on one row. Check the merged names before reporting.',
      },
      productivityTrend: 'Productivity trend',
      weeklyProductivity: 'Weekly productivity',
      subtitles: {
        forDate: 'For {date}',
        weekOf: 'Week of {date}',
        target: 'Target {hours}h / week',
        completedPercent: '{percent}% of logged items completed',
      },
      records: {
        dailyWorklog: 'Daily worklog',
        dailyWorklogEntry: 'Daily worklog entry',
        generalProject: 'General',
        taskFallback: 'Task {index}',
        categoryDaily: 'Daily',
        categoryTask: 'Task',
      },
      overtimeCard: {
        title: 'Overtime overview',
        target: 'Target {hours}h / week',
        over: '{hours}h over',
        onTarget: 'On target',
        regular: 'Regular',
        overtime: 'Overtime',
        remaining: 'Remaining',
      },
      table: {
        date: 'Date',
        task: 'Task',
        project: 'Project',
        description: 'Description',
        hours: 'Hours',
        status: 'Status',
        dates: 'Dates',
        daysWorked: 'Days',
        totalHours: 'Total hours',
        days: '{count} days',
        mergedNames: '{count} names',
        empty: 'No matching worklog entries found for the selected filters.',
      },
      taskCard: {
        timeSpent: 'time spent',
      },
      arrows: {
        prev: '←',
        next: '→',
      },
    },
    reports: {
      eyebrow: 'Reporting & analytics',
      summaryDetails: {
        filteredWorklogs: 'Across filtered worklogs',
        completionRate: 'Completion rate',
        projectsInScope: 'Projects in scope',
        expectedWorkload: 'Against expected workload',
      },
      projectMeta: '{hours}h logged • {count} tasks',
      taskCompletionDetails: {
        completed: 'Tasks in completed state',
        pending: 'Tasks still active or planned',
        average: 'Based on actual task minutes',
      },
      pageTitle: 'Worklog analytics',
      pageDescription: 'Insights generated from the live worklog and task records in the workspace.',
      exportCsv: 'Export CSV',
      exportPdf: 'Export PDF',
      loading: 'Loading analytics…',
      summary: {
        totalLoggedHours: 'Total logged hours',
        completedTasksPercent: 'Completed tasks %',
        activeProjects: 'Active projects',
        overtimeHours: 'Overtime hours',
      },
      emptyState: 'No worklog or task data is available for the selected range yet.',
      hoursByProject: 'Hours by project',
      projectTimeBreakdown: 'Project time breakdown',
      noProjectHours: 'No project hours to show yet.',
      overtime: 'Overtime',
      normalVsOvertime: 'Normal vs overtime',
      normalHours: 'Normal hours',
      overtimeHoursLabel: 'Overtime hours',
      projectReports: 'Project reports',
      projectDeliveryOverview: 'Project delivery overview',
      completed: 'Completed',
      avgTime: 'Avg. time',
      noProjectData: 'No project data available.',
      taskAnalytics: 'Task analytics',
      taskCompletion: 'Task completion',
      completedTasks: 'Completed tasks',
      pendingTasks: 'Pending tasks',
      averageTimePerTask: 'Average time per task',
      noTaskActivity: 'No task activity found for this view.',
      noTaskCompletion: 'No task completion data available.',
      filters: {
        from: 'From',
        to: 'To',
        project: 'Project',
        allProjects: 'All projects',
        taskStatus: 'Task status',
        allStatuses: 'All statuses',
        completed: 'Completed',
        inProgress: 'In progress',
        planned: 'Planned',
        blocked: 'Blocked',
        user: 'User',
        allUsers: 'All users',
      },
    },
    notifications: {
      title: 'Notifications',
      pageTitle: 'Alerts and reminders',
      pageDescription: 'Keep track of task deadlines, timesheet reminders, approvals, and meeting alerts.',
      countLabel: '{count} alerts',
      loading: 'Loading notifications…',
      emptyState: 'Nothing needs your attention right now.',
      categoryDefault: 'Notification',
      statusDefault: 'New',
      received: 'Received:',
      noDetails: 'No further details.',
      error: 'Unable to load notifications.',
      markSeen: 'Seen',
      remindLater: 'Remind me later',
      snoozeOptions: {
        oneHour: 'In 1 hour',
        fourHours: 'In 4 hours',
        tomorrow: 'Tomorrow',
        nextWeek: 'Next week',
      },
      snoozedUntil: 'Hidden until',
      actionFailed: 'Could not update the notification. Check your connection and try again.',
    },
    projects: {
      pageTitle: 'Project management dashboard',
      pageDescription: 'Coordinate delivery, monitor utilization, and keep worklog activity aligned with project goals.',
      newProject: 'New Project',
      summary: {
        totalProjects: 'Total projects',
        activeProjects: 'Active projects',
        atRiskProjects: 'At-risk projects',
        totalLoggedHours: 'Total logged hours',
      },
      searchPlaceholder: 'Search projects',
      allStatuses: 'All statuses',
      newest: 'Newest',
      highestProgress: 'Highest progress',
      mostLoggedHours: 'Most logged hours',
      loading: 'Loading projects…',
      emptyState: 'No projects yet.',
      statusPrompt: 'Select new status',
      memberPrompt: 'Add comma separated member names',
      saveFailed: 'Could not save the project to the server. Check your connection and try again.',
      eyebrow: 'Project workspace',
      error: 'Unable to load projects.',
      defaultManager: 'Team lead',
      summaryDetails: {
        portfolio: 'Across portfolio',
        inDelivery: 'In delivery',
        needAttention: 'Need attention',
        activeWork: 'Across active work',
      },
      statuses: {
        planning: 'Planning',
        active: 'Active',
        atRisk: 'At Risk',
        onHold: 'On Hold',
        completed: 'Completed',
        cancelled: 'Cancelled',
      },
      card: {
        client: 'Client',
        projectNumber: 'Project number',
        manager: 'Manager',
        progress: 'Progress',
        hoursLogged: '{hours}h logged',
        members: '{count} members',
        openDetails: 'Open details',
        edit: 'Edit',
        changeStatus: 'Change status',
        addMembers: 'Add members',
        archive: 'Archive',
        delete: 'Delete',
      },
      detail: {
        editProject: 'Edit project',
        updateStatus: 'Update status',
        tabs: {
          overview: 'Overview',
          worklogs: 'Worklogs',
          team: 'Team',
          reports: 'Reports',
          settings: 'Settings',
        },
        manager: 'Manager',
        timeline: 'Timeline',
        budget: 'Budget',
        logged: 'Logged',
        deliveryProgress: 'Delivery progress',
        date: 'Date',
        user: 'User',
        task: 'Task',
        hours: 'Hours',
        utilization: 'Utilization',
        deliveryConfidence: 'Delivery confidence',
        stable: 'Stable',
        needsAttention: 'Needs attention',
        status: 'Status',
        notificationsEnabled: 'Notifications enabled for the project team.',
        reviewCadence: 'Default review cadence: weekly.',
        currentStatus: 'Current status',
        teamHealth: 'Team health',
        activeContributors: '{count} active contributors',
        worklogFocus: 'Worklog focus',
        entriesThisCycle: '{count} entries this cycle',
      },
    },
    meetings: {
      pageTitle: 'Calendar-based meeting management',
      pageDescription: 'Coordinate meetings, track action items, and connect them to worklog delivery.',
      remindersEnabled: 'Meeting reminders enabled',
      remindersBlocked: 'Browser notifications blocked',
      remindersNotEnabled: 'Meeting reminders not enabled',
      notificationsUnavailable: 'Browser notifications unavailable',
      enableReminders: 'Enable reminders',
      newMeeting: 'New meeting',
      summary: {
        totalMeetings: 'Total meetings',
        totalMeetingsDetail: 'All scheduled meetings across the calendar.',
        upcomingMeetings: 'Upcoming meetings',
        upcomingMeetingsDetail: 'Meetings that are not yet completed or cancelled.',
        completedMeetings: 'Completed meetings',
        completedMeetingsDetail: 'Meetings that have been marked as completed.',
        totalMeetingHours: 'Total meeting hours',
        totalMeetingHoursDetail: 'Combined scheduled meeting time for the selected period.',
      },
      weekView: 'Week view',
      dayView: 'Day view',
      agenda: 'Agenda',
      searchPlaceholder: 'Search meetings',
      allStatuses: 'All statuses',
      date: 'Date',
      duration: 'Duration',
      calendar: 'Calendar',
      meetingSchedule: 'Meeting schedule',
      loading: 'Loading meetings…',
      noMeetings: 'No meetings for the selected date yet.',
      reviewHistory: 'Review history',
      historyTitle: 'Past, current, upcoming',
      worklogLinkage: 'Worklog linkage',
      worklogLinkageDescription: 'Every meeting can be linked to a worklog entry and automatically contribute to the day’s tracked meeting hours.',
      findMeetings: 'Find meetings',
      filters: 'Filters',
      statusAndRecurrence: 'Status and recurrence',
      sorting: 'Sorting',
      dateOrDuration: 'By date or duration',
      history: 'History',
      auditReady: 'Audit-ready view',
      open: 'Open',
      edit: 'Edit',
      search: 'Search',
      defaultProject: 'General',
      defaultParticipants: 'Team',
      untitledMeeting: 'Untitled meeting',
      oneTime: 'One-time',
      pending: 'Pending',
      noMeetingDetails: 'No meeting details available.',
      reminderTitle: '{minutes}-min Reminder: {title}',
      reschedulePrompt: 'Reschedule meeting to (YYYY-MM-DD)?',
      details: 'Details',
      agendaLabel: 'Agenda',
      notesLabel: 'Notes',
      actionItems: 'Action items',
      actionDone: 'Done',
      actionPending: 'Pending',
      dueBy: 'due',
    },
    calendar: {
      pageTitle: 'Calendar module',
      pageDescription: 'Select a date and view saved worklog details or holiday status for that day.',
      japaneseCalendar: 'Japanese calendar',
      legend: 'Legend',
      selectedDate: 'Selected date',
      holiday: 'Holiday',
      currentDate: 'Current date',
      dayDetails: 'Day details',
      selectedDateLabel: 'Selected date:',
      holidayMessage: 'This day is marked as a holiday:',
      noSavedWorklog: 'No saved worklog for this date yet.',
      createWorklog: 'Create worklog',
      savedWorklog: 'Saved worklog',
      savedAt: 'Saved at:',
      status: 'Status',
      executionDetails: 'Execution details',
      plannedItems: 'Planned items',
      summary: 'Summary',
      plannedMinutes: 'Planned minutes',
      actualMinutes: 'Actual minutes',
      meetingTime: 'Meeting time',
      completion: 'Completion',
      openWorklogPage: 'Open worklog page',
      notAvailable: 'Not available',
      notRecorded: 'Not recorded',
      noNotes: 'No notes',
      noDescription: 'No description',
      noProject: 'No project',
      untitledItem: 'Untitled item',
      item: 'Item',
      today: 'Today',
      workday: 'Workday',
      sunday: 'Sun',
      saturday: 'Sat',
      weeklyCalendar: 'Weekly calendar',
      tapADay: 'Tap a day',
      previousWeek: 'Previous week',
      nextWeek: 'Next week',
    },
    modal: {
      meeting: {
        createTitle: 'Create meeting',
        editTitle: 'Edit meeting',
        description: 'Plan, schedule, and connect meetings to project worklogs.',
        close: 'Close',
        title: 'Title',
        project: 'Project',
        date: 'Date',
        startTime: 'Start time',
        duration: 'Duration (min)',
        status: 'Status',
        participants: 'Participants',
        recurrence: 'Recurrence',
        descriptionLabel: 'Description',
        agenda: 'Agenda',
        notes: 'Notes',
        cancel: 'Cancel',
        save: 'Save meeting',
      },
      project: {
        createTitle: 'Create project',
        editTitle: 'Edit project',
        description: 'Capture scope, delivery expectations, and team ownership.',
        close: 'Close',
        projectNumber: 'Project number',
        projectNumberPlaceholder: 'e.g. PRJ-1042',
        projectName: 'Project name',
        client: 'Client',
        descriptionLabel: 'Description',
        startDate: 'Start date',
        endDate: 'End date',
        budgetHours: 'Budget hours',
        manager: 'Manager',
        teamMembers: 'Team members',
        status: 'Status',
        cancel: 'Cancel',
        save: 'Save project',
      },
    },
    profile: {
      title: 'Profile',
      heading: 'Employee identity and account details for your worklog profile, with editable personal fields and read-only company-managed information.',
      saveButton: 'Save profile',
      editButton: 'Edit profile',
      cancelButton: 'Cancel',
      welcome: 'Welcome aboard!',
      completeTitle: 'Complete your profile',
      completeDescription: 'Your profile is missing some details. Add job title, phone, location, or manager to unlock improved collaboration and reminders.',
      onboardingDescription: 'Thanks for signing up — finish your profile details so the team can find you and you receive better notifications.',
      personalInfoTitle: 'Personal Information',
      personalInfoDescription: 'Editable fields are marked with personal details that help coworkers find you.',
      fullName: 'Full name',
      email: 'Email',
      employeeId: 'Employee ID',
      jobTitle: 'Job title',
      department: 'Department',
      accountStatus: 'Account status',
      phone: 'Phone',
      location: 'Location',
      manager: 'Manager',
      placeholder: 'Not available',
      notAssigned: 'Not assigned',
      success: 'Profile updated successfully.',
      saveError: 'Unable to save profile.',
      blankName: 'Full name cannot be blank.',
      noRecentActivity: 'No recent activity',
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      employmentTitle: 'Employment Information',
      employmentDescription: 'Company-managed details are shown as read-only and can be confirmed with HR.',
      joiningDate: 'Joining date',
      role: 'Role',
      defaultRole: 'Employee',
      accountSettingsTitle: 'Account Settings',
      accountSettingsDescription: 'Manage authentication hints, login details, and company access levels.',
      editableFields: 'Editable: full name, email, employee ID, department, job title, phone, location, manager',
      accessLevel: 'Access level',
      defaultAccessLevel: 'Standard user',
      lastLogin: 'Last login',
      profileVisibility: 'Profile visibility',
      defaultVisibility: 'Internal only',
      placeholders: {
        fullName: 'Full name',
        email: 'Email address',
        employeeId: 'Employee ID',
        phone: 'Phone number',
        location: 'Office location',
        department: 'Department',
        manager: 'Manager name',
        jobTitle: 'Job title',
      },
    },
  },
  Japanese: {
    appName: 'ワークパルス',
    appTagline: 'エンタープライズの業務オーケストレーション',
    holidays: {
      newYear: '元日',
      comingOfAge: '成人の日',
      nationalFoundation: '建国記念の日',
      emperorsBirthday: '天皇誕生日',
      vernalEquinox: '春分の日',
      showa: '昭和の日',
      constitutionMemorial: '憲法記念日',
      greenery: 'みどりの日',
      children: 'こどもの日',
      marine: '海の日',
      mountain: '山の日',
      respectForTheAged: '敬老の日',
      autumnalEquinox: '秋分の日',
      sports: 'スポーツの日',
      culture: '文化の日',
      laborThanksgiving: '勤労感謝の日',
    },
    header: {
      workspace: 'ワークスペース',
      navigationHub: 'ナビゲーションハブ',
      quickStats: {
        hours: '作業時間',
        meetings: '会議',
        tasks: 'タスク',
      },
    },
    nav: {
      dashboard: 'ダッシュボード',
      planner: 'ワークログ計画',
      worklog: 'ワークログ承認',
      calendar: 'カレンダー',
      timesheet: 'タイムシート',
      reports: 'レポート',
      notifications: '通知',
      projects: 'プロジェクト',
      meetings: '会議',
    },
    menu: {
      profile: 'プロフィール',
      settings: '設定',
      worklogs: 'ワークログ',
      reports: 'レポート',
      notifications: '通知',
      signOut: 'サインアウト',
    },
    settings: {
      settingsLabel: '設定',
      pageTitle: 'アプリ設定',
      pageDescription: '言語、テーマ、カラーパレットを管理します。',
      languageTitle: '言語',
      languageDescription: 'アプリの表示言語を選択します。',
      themeTitle: 'テーマモード',
      themeDescription: 'ライトモードとダークモードを切り替えます。',
      lightMode: 'ライトモード',
      darkMode: 'ダークモード',
      themeColorsTitle: 'テーマカラー',
      themeColorsDescription: '現在のモードのカラーパレットを調整します。',
      resetTheme: 'デフォルトに戻す',
      resetThemeDescription: '元のテーマに戻します。',
      colors: {
        accent: { label: 'アクセント', description: '主要な操作と強調表示' },
        background: { label: '背景', description: 'ページの背景色' },
        surface: { label: 'サーフェス', description: 'カードとパネル' },
        textPrimary: { label: 'テキスト', description: '主要な文字色' },
        textSecondary: { label: '補助テキスト', description: '控えめなラベルと補足' },
      },
    },
    account: {
      profileCompletion: 'プロフィール完了',
    },
    notFound: {
      message: 'ページが見つかりません。ナビゲーションメニューをご利用ください。',
    },
    common: {
      save: '保存',
      saving: '保存中...',
      cancel: 'キャンセル',
      edit: '編集',
      backToLogin: 'ログインに戻る',
      createAccount: 'アカウント作成',
      tryRecoveryAgain: '再試行',
      loading: '読み込み中...',
      completeProfile: 'プロフィールを完了',
      signOut: 'サインアウト',
      tbd: '未定',
      statuses: {
        planned: '計画済み',
        inProgress: '進行中',
        submitted: '提出済み',
        approved: '承認済み',
        rejected: '却下',
        completed: '完了',
        cancelled: 'キャンセル',
        onTrack: '順調',
      },
    },
    auth: {
      loginTitle: '安全なログイン',
      loginSubtitle: '日々の作業計画と分析ダッシュボードにアクセスします。',
      employeeId: '社員ID',
      password: 'パスワード',
      rememberMe: 'ログイン状態を保持',
      forgotPassword: 'パスワードを忘れましたか？',
      loginButton: 'ログイン',
      noAccount: 'アカウントをお持ちでないですか？',
      registerLink: '登録',
      registerTitle: 'アカウントを作成',
      registerSubtitle: '社員プロフィールを設定してチームに参加しましょう。',
      fullName: '氏名',
      companyEmail: '会社メール',
      department: '部署',
      confirmPassword: 'パスワード確認',
      createAccountButton: 'アカウント作成',
      alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
      loginLink: 'ログイン',
      passwordMinLength: 'パスワードは8文字以上で入力してください。',
      passwordsMustMatch: 'パスワードが一致しません。',
      registrationFailed: '登録に失敗しました。もう一度お試しください。',
      loginFailed: 'ログインに失敗しました。認証情報を確認してください。',
      sessionExpired: 'セッションの有効期限が切れたため、直近の変更が保存されていない可能性があります。再度サインインしてください。',
      placeholders: {
        fullName: '山田 太郎',
        email: 'name@company.com',
        employeeId: 'EMP-001',
        department: '技術部',
      },
    },
    recovery: {
      title: 'パスワードをお忘れの方',
      subtitle: 'セキュリティ質問に答えて、メール確認なしでパスワードをリセットします。',
      recoverTitle: 'アカウントを回復',
      recoverSubtitle: 'セキュリティ質問に答えて、メール確認なしでパスワードをリセットします。',
      companyEmail: '会社メール',
      employeeId: '社員ID',
      selectQuestions: '以下の質問から3つを選び、回答してください。',
      answerPlaceholder: '回答を入力',
      verifyAnswers: '回答を確認',
      startRecovery: '回復を開始',
      backToLogin: 'ログインに戻る',
      createAccount: 'アカウント作成',
      errors: {
        missingIdentity: '社員IDと会社メールの両方を入力してください。',
        selectThree: '続行するには、質問を3つ選んで回答してください。',
        exactlyThree: 'セキュリティ質問をちょうど3つ選択してください。',
        answerAll: '選択したセキュリティ質問すべてに回答してください。',
      },
    },
    resetPassword: {
      title: 'パスワードをリセット',
      subtitle: '回復トークンを使って、新しい安全なパスワードを選びます。',
      heading: '新しいパスワードを設定',
      newPassword: '新しいパスワード',
      confirmPassword: '新しいパスワード確認',
      resetButton: 'パスワードをリセット',
      success: 'パスワードをリセットしました。ログイン画面に移動します...',
      emptyFields: '両方のパスワード欄を入力してください。',
      passwordMinLength: 'パスワードは8文字以上で入力してください。',
      passwordsMustMatch: 'パスワードが一致しません。',
      backToLogin: 'ログインに戻る',
      tryRecoveryAgain: '再試行',
    },
    security: {
      title: 'セキュリティ質問を設定',
      subtitle: '後でアカウントを回復できるように、今すぐこれらの質問に答えてください。',
      loading: 'セキュリティ質問を読み込み中...',
      answerPlaceholder: '回答を入力',
      saveButton: '回答を保存',
      saving: '保存中...',
      answerAll: 'すべてのセキュリティ質問に回答してください。',
      saved: 'セキュリティ質問を保存しました。',
    },
    dashboard: {
      badge: 'ワークパルス コマンドセンター',
      title: 'ワークログ ダッシュボード',
      description: 'リアルタイムのテーマ対応分析で、生産性・タスク状況・作業負荷のバランスを一目で確認できます。',
      filters: {
        daily: '日次',
        weekly: '週間',
        monthly: '月次',
      },
      overview: {
        totalWorkHours: '総作業時間',
        totalWorkHoursDescription: 'この期間は安定して集中できています',
        completedTasks: '完了タスク',
        completedTasksDescription: '絞り込んだワークログ全体',
        pendingTasks: '未完了タスク',
        pendingTasksDescription: 'フォローアップが必要です',
        inProgress: '進行中',
        inProgressDescription: '現在対応中のタスク',
        overdue: '期限超過',
        overdueDescription: 'ブロック中または停滞中の項目',
      },
      sections: {
        workHours: '作業時間と生産性',
        workHoursDescription: '選択期間の納期・進捗をより明確に確認できます。',
        productivity: '生産性',
        workHoursCard: '作業時間',
        taskCompletion: 'タスク完了率',
        liveRange: 'ライブ範囲',
        loading: '読み込み中',
        completionTrend: '完了傾向',
        taskHistory: 'タスク履歴',
        estimatedTime: '予定時間',
      },
      workHoursTrend: '前{period}比 {delta}',
      workHoursTrendNone: '比較データなし',
      periods: {
        daily: '日',
        weekly: '週',
        monthly: '月',
      },
      pendingTasksTitle: '保留中のタスク',
      pendingTasksDescription: 'この期間に対応が必要な次のアクションです。',
      pendingTasksActive: 'アクティブ',
      pendingTasksNone: '保留中のタスクはありません',
      pendingTaskDueLabel: '期限',
      pendingTaskPriorityLabel: '優先度',
      pendingTaskEstimateLabel: '見積り',
      pendingTasksEmptyDescription: '今日は予定がクリアです。',
      insightsTitle: 'インサイトとおすすめ',
      insightsDescription: '次に注目すべきトレンドの要約です。',
      insightsAction: '自動同期済み',
      insights: {
        completionRateDescription: 'フィルタ済みタスクに基づく完了率です。',
        taskHistoryDescription: '現在のワークスペース内のタスク合計です。',
        estimatedTimeDescription: '日付範囲の予想作業時間です。',
      },
      error: 'ダッシュボードのデータを読み込めませんでした。',
      emptyRange: 'この{period}の期間にはまだ作業時間が記録されていません。上の期間を切り替えるか、ワークログ承認ページで実績を入力してください。',
    },
    planner: {
      pageTitle: '日次作業プランナー',
      pageDescription: '日付を選択し、朝のタスクや会議を入力して計画を保存します。',
      selectedWeek: '選択中の週間',
      weeklyCalendarLabel: '週間カレンダー',
      selectedDate: '選択日',
      holidayWeekend: '祝日 / 週末',
      currentDate: '現在の日付',
      tapADay: '日をタップ',
      messages: {
        holidayNotice: '{holiday} の保存された計画がありません。この日付の計画を開始してください。',
        noSavedWorklog: 'この日付の計画データはまだ保存されていません。',
        savedWorklogLoaded: 'この日の保存済みワークログが読み込まれました。',
      },
      morningPlannerTitle: '朝のプランナー',
      morningPlannerDescription: '朝のタスクと会議を入力して、プレビュー後に保存します。',
      previewButton: 'プレビュー',
      saveButton: '計画を保存',
      documentation: 'ドキュメンテーション',
      others: 'その他',
      plannedMinutes: '計画分',
      description: '説明',
      totalPlannedTime: '合計計画時間',
      goal: '目標: 8時間',
      readyToSave: '保存可能',
      needMore: '{remaining} 追加必要',
      previewTitle: 'プレビュー',
      previewDescription: '保存前にタスクと会議の内容を確認してください。',
      draft: '下書き',
      totalPlanned: '合計計画',
      tasksPreview: 'タスクプレビュー',
      meetingsPreview: '会議プレビュー',
      taskSectionTitle: 'タスク計画',
      taskSectionDescription: '作業項目、予定分、ステータスを整理します。',
      addTask: 'タスクを追加',
      taskNameLabel: 'タスク名',
      projectLabel: 'プロジェクト',
      taskDescriptionLabel: 'タスクの説明',
      taskStatusLabel: 'ステータス',
      meetingSectionTitle: '会議の計画',
      meetingSectionDescription: '会議をスケジュールし、メモを記録します。',
      addMeeting: '会議を追加',
      meetingLabel: '会議',
      meetingScheduledDescription: '予定された会議の詳細',
      meetingTitleLabel: '会議名',
      meetingFromLabel: '開始',
      meetingToLabel: '終了',
      meetingDescriptionLabel: '説明',
      meetingTypeLabel: '会議タイプ',
      meetingTypes: {
        meeting: '会議',
        call: '通話',
        review: 'レビュー',
      },
      durationLabel: '時間',
      minutesLabel: '分',
      planned: '計画',
      noDocumentationNotes: 'ドキュメントのメモはありません。',
      noOtherNotes: 'その他のメモはありません。',
      untitledTask: '無題のタスク',
      noProject: 'プロジェクトなし',
      loadingProjects: 'プロジェクトを読み込み中…',
      noProjectsYet: 'プロジェクトが未登録です。プロジェクトページで追加してください。',
      noProjectSelected: 'プロジェクト未選択',
      noDescriptionAdded: '説明はありません。',
      untitledMeeting: '無題の会議',
      noTimeSelected: '時間未選択',
      validation: {
        eachTaskNeedsTitle: '各タスクにはタイトルが必要です。',
        minutesCannotBeNegative: '計画分はマイナスにできません。',
        exceeds24Hours: '1日の計画が24時間を超えています。',
        meetingTitleEmpty: '会議タイトルは空にできません。',
        resolveBeforeSaving: '保存前にプランナーの入力エラーを解決してください。',
        previewBeforeSaving: 'まずプランナーをプレビューしてください。',
        need8Hours: '保存するには少なくとも8時間の計画が必要です。',
        savedSuccess: '計画を保存しました。日付を選択すると再編集できます。',
        previewReady: 'プレビューの準備ができました。以下を確認して「計画を保存」を押してください。',
        autosaved: '下書きを自動保存しました。',
        saveFailed: 'サーバーに計画を保存できませんでした。接続を確認して再試行してください。',
        autosaveFailed: '自動保存がサーバーに届きませんでした。変更は一時的にローカルへ保持しています。',
        resolveBeforePreview: 'プレビュー前にプランナーの入力エラーを解決してください。',
      },
      placeholders: {
        minutes: '分',
        taskName: 'タスク名',
        projectName: 'プロジェクト名',
        taskDescription: 'タスクの説明',
        meetingName: '会議名',
        meetingDescription: '会議の説明',
        notesForDocumentation: 'ドキュメント作業のメモ',
        notesForOtherActivities: 'その他の活動メモ',
      },
      eightHoursReached: '8時間分が計画されています',
    },
    worklog: {
      eyebrow: '日次の実行',
      detailTypes: {
        task: 'タスク',
        meeting: '会議',
        documentation: 'ドキュメンテーション',
        other: 'その他',
      },
      taskFallback: 'タスク{index}',
      meetingFallback: '会議{index}',
      othersTitle: 'その他',
      plannedMinutesBadge: '計画 {minutes}分',
      pageTitle: 'ワークログ実行',
      pageDescription: 'カレンダーで計画日を開き、計画項目を確認し、実績の詳細を更新できます。',
      weeklyCalendar: '週間カレンダー',
      chooseAnyDay: '任意の日を選んでそのワークログを編集',
      plannedDay: '計画日',
      plannedDayDescription: 'この日の計画データを表示します。編集モードでは実績時間項目が開放されます。',
      editExecution: '実績を編集',
      cancelEdit: '編集をキャンセル',
      noPlanner: 'この日付の計画はまだありませんが、実績の詳細を記録して保存できます。',
      plannedVsActual: '計画 vs 実績',
      overview: '日次実行サマリー',
      extraTime: '超過',
      lessTime: '不足',
      onTarget: '目標内',
      planned: '計画',
      actual: '実績',
      plannedItems: '計画項目と実績工数',
      actualMinutes: '実績時間',
      notes: 'メモ',
      noNotesYet: 'メモはまだありません。',
      statusSummary: 'ステータスサマリー',
      currentState: '現在の状態',
      difference: '差分',
      review: '確認',
      reviewDescription: '計画内容はそのまま残し、編集時に実績の詳細だけを更新します。',
      saveWorklog: 'ワークログを保存',
      saveSuccess: 'ワークログを保存しました。',
      saveFailed: 'サーバーにワークログを保存できませんでした。接続を確認して再試行してください。',
      loadFailed: 'この日のデータをサーバーから取得できませんでした。接続を確認して再試行してください。',
      sessionStatus: 'セッション状態',
      sessionStatuses: {
        pendingToStart: '開始前',
        ongoing: '進行中',
        completed: '完了',
      },
      minutes: '分',
    },
    timesheet: {
      pageTitle: 'ワークログ時間サマリーとタスク時間',
      pageDescription: '別途タイムトラッキングを作らずに、ワークログベースの生産性・タスク時間・残業時間を確認できます。',
      anchorDate: '基準日',
      loading: 'ワークログ分析を読み込み中…',
      emptyTitle: 'まだワークログデータが保存されていません。',
      emptyDescription: '日次ワークログから保存すると、この分析モジュールに表示されます。',
      totalLogged: '合計記録',
      totalLoggedSubtitle: '保存済み全ワークログ対象',
      dailyHours: '日次時間',
      weeklyHours: '週間時間',
      monthlyHours: '月次時間',
      remainingRequired: '残り必要時間',
      completedTasks: '完了タスク',
      taskLevelHours: 'タスク単位時間',
      breakdownTitle: 'タスクとプロジェクトの内訳',
      entries: '{count}件',
      timeDistribution: '時間配分',
      projectHours: 'プロジェクト時間',
      worklogHistory: 'ワークログ履歴',
      filterAndReview: 'ワークログ項目を絞り込み確認',
      filtersEnabled: 'フィルター有効',
      startDate: '開始日',
      endDate: '終了日',
      project: 'プロジェクト',
      task: 'タスク',
      status: 'ステータス',
      allProjects: 'すべてのプロジェクト',
      allTasks: 'すべてのタスク',
      allStatuses: 'すべてのステータス',
      emptyFilters: '選択したフィルターに一致するワークログがありません。',
      groupingLabel: '表示方法',
      groupByTask: 'タスクごとに1行',
      groupByDate: '日ごとに1行',
      matchLabel: '名称の統合',
      matchModes: {
        exact: '完全一致のみ',
        similar: '類似する名称',
        loose: '関連する名称',
      },
      matchHint: {
        exact: 'まったく同じ名称の項目だけをまとめます。',
        similar: '同じ作業の言い換えをまとめます。',
        loose: '語句の大半が共通する項目をまとめます。統合された名称を確認してください。',
      },
      productivityTrend: '生産性の傾向',
      weeklyProductivity: '週間生産性',
      subtitles: {
        forDate: '{date} の実績',
        weekOf: '{date} の週',
        target: '目標 週{hours}時間',
        completedPercent: '記録済み項目の{percent}%が完了',
      },
      records: {
        dailyWorklog: '日次ワークログ',
        dailyWorklogEntry: '日次ワークログの記録',
        generalProject: '一般',
        taskFallback: 'タスク{index}',
        categoryDaily: '日次',
        categoryTask: 'タスク',
      },
      overtimeCard: {
        title: '残業の概要',
        target: '目標 週{hours}時間',
        over: '{hours}時間 超過',
        onTarget: '目標内',
        regular: '通常',
        overtime: '残業',
        remaining: '残り',
      },
      table: {
        date: '日付',
        task: 'タスク',
        project: 'プロジェクト',
        description: '説明',
        hours: '時間',
        status: 'ステータス',
        dates: '期間',
        daysWorked: '日数',
        totalHours: '合計時間',
        days: '{count}日',
        mergedNames: '表記{count}件',
        empty: '選択したフィルターに一致するワークログがありません。',
      },
      taskCard: {
        timeSpent: '経過時間',
      },
      arrows: {
        prev: '←',
        next: '→',
      },
    },
    reports: {
      eyebrow: 'レポートと分析',
      summaryDetails: {
        filteredWorklogs: '絞り込んだワークログ全体',
        completionRate: '完了率',
        projectsInScope: '対象プロジェクト',
        expectedWorkload: '想定作業量との比較',
      },
      projectMeta: '{hours}時間 記録 • {count}件のタスク',
      taskCompletionDetails: {
        completed: '完了状態のタスク',
        pending: '進行中または計画中のタスク',
        average: '実績のタスク時間に基づく',
      },
      pageTitle: 'ワークログ分析',
      pageDescription: 'ワークスペース内のライブなワークログとタスク記録から分析結果を生成します。',
      exportCsv: 'CSVを出力',
      exportPdf: 'PDFを出力',
      loading: '分析を読み込み中…',
      summary: {
        totalLoggedHours: '合計作業時間',
        completedTasksPercent: '完了タスク率',
        activeProjects: '進行中プロジェクト',
        overtimeHours: '残業時間',
      },
      emptyState: '選択範囲にワークログまたはタスクのデータがありません。',
      hoursByProject: 'プロジェクト別時間',
      projectTimeBreakdown: 'プロジェクト時間内訳',
      noProjectHours: '表示するプロジェクト時間がありません。',
      overtime: '残業',
      normalVsOvertime: '通常時間と残業時間',
      normalHours: '通常時間',
      overtimeHoursLabel: '残業時間',
      projectReports: 'プロジェクトレポート',
      projectDeliveryOverview: 'プロジェクト納期概要',
      completed: '完了',
      avgTime: '平均時間',
      noProjectData: 'プロジェクトデータがありません。',
      taskAnalytics: 'タスク分析',
      taskCompletion: 'タスク完了率',
      completedTasks: '完了タスク',
      pendingTasks: '保留タスク',
      averageTimePerTask: 'タスクあたり平均時間',
      noTaskActivity: 'この表示に該当するタスク活動がありません。',
      noTaskCompletion: 'タスク完了データがありません。',
      filters: {
        from: '開始',
        to: '終了',
        project: 'プロジェクト',
        allProjects: 'すべてのプロジェクト',
        taskStatus: 'タスクステータス',
        allStatuses: 'すべてのステータス',
        completed: '完了',
        inProgress: '進行中',
        planned: '計画済み',
        blocked: 'ブロック中',
        user: 'ユーザー',
        allUsers: 'すべてのユーザー',
      },
    },
    notifications: {
      title: '通知',
      pageTitle: 'アラートとリマインダー',
      pageDescription: 'タスクの期限、タイムシートのリマインダー、承認、会議アラートを確認できます。',
      countLabel: '{count}件の通知',
      loading: '通知を読み込み中…',
      emptyState: '対応が必要な通知はありません。',
      categoryDefault: '通知',
      statusDefault: '新規',
      received: '受信日時:',
      noDetails: '詳細情報はありません。',
      error: '通知を読み込めませんでした。',
      markSeen: '確認済み',
      remindLater: '後で通知',
      snoozeOptions: {
        oneHour: '1時間後',
        fourHours: '4時間後',
        tomorrow: '明日',
        nextWeek: '来週',
      },
      snoozedUntil: '次の通知予定',
      actionFailed: '通知を更新できませんでした。接続を確認して再試行してください。',
    },
    projects: {
      pageTitle: 'プロジェクト管理ダッシュボード',
      pageDescription: '納期の調整、稼働状況の確認、ワークログ活動との整合を保ちます。',
      newProject: '新規プロジェクト',
      summary: {
        totalProjects: 'プロジェクト数',
        activeProjects: '進行中プロジェクト',
        atRiskProjects: '要注意プロジェクト',
        totalLoggedHours: '合計ログ時間',
      },
      searchPlaceholder: 'プロジェクトを検索',
      allStatuses: 'すべてのステータス',
      newest: '最新順',
      highestProgress: '進捗率順',
      mostLoggedHours: 'ログ時間順',
      loading: 'プロジェクトを読み込み中…',
      emptyState: 'プロジェクトはまだありません。',
      statusPrompt: '新しいステータスを選択',
      memberPrompt: 'メンバー名をカンマ区切りで追加',
      saveFailed: 'サーバーにプロジェクトを保存できませんでした。接続を確認して再試行してください。',
      eyebrow: 'プロジェクトワークスペース',
      error: 'プロジェクトを読み込めませんでした。',
      defaultManager: 'チームリード',
      summaryDetails: {
        portfolio: 'ポートフォリオ全体',
        inDelivery: '進行中',
        needAttention: '要対応',
        activeWork: '稼働中の作業全体',
      },
      statuses: {
        planning: '計画中',
        active: '進行中',
        atRisk: '要注意',
        onHold: '保留中',
        completed: '完了',
        cancelled: 'キャンセル',
      },
      card: {
        client: '顧客',
        projectNumber: 'プロジェクト番号',
        manager: '担当マネージャー',
        progress: '進捗',
        hoursLogged: '{hours}時間 記録',
        members: 'メンバー{count}名',
        openDetails: '詳細を開く',
        edit: '編集',
        changeStatus: 'ステータスを変更',
        addMembers: 'メンバーを追加',
        archive: 'アーカイブ',
        delete: '削除',
      },
      detail: {
        editProject: 'プロジェクトを編集',
        updateStatus: 'ステータスを更新',
        tabs: {
          overview: '概要',
          worklogs: 'ワークログ',
          team: 'チーム',
          reports: 'レポート',
          settings: '設定',
        },
        manager: '担当マネージャー',
        timeline: '期間',
        budget: '予算',
        logged: '記録済み',
        deliveryProgress: '納品進捗',
        date: '日付',
        user: 'ユーザー',
        task: 'タスク',
        hours: '時間',
        utilization: '稼働率',
        deliveryConfidence: '納品確度',
        stable: '安定',
        needsAttention: '要対応',
        status: 'ステータス',
        notificationsEnabled: 'プロジェクトチームへの通知が有効です。',
        reviewCadence: '既定のレビュー頻度：毎週',
        currentStatus: '現在のステータス',
        teamHealth: 'チーム状況',
        activeContributors: '稼働メンバー{count}名',
        worklogFocus: 'ワークログ状況',
        entriesThisCycle: '今サイクル{count}件',
      },
    },
    meetings: {
      pageTitle: 'カレンダー型会議管理',
      pageDescription: '会議を調整し、アクション項目を追跡してワークログ納期に結びつけます。',
      remindersEnabled: '会議リマインダー有効',
      remindersBlocked: 'ブラウザ通知がブロックされています',
      remindersNotEnabled: '会議リマインダー未有効',
      notificationsUnavailable: 'ブラウザ通知を利用できません',
      enableReminders: 'リマインダーを有効化',
      newMeeting: '新規会議',
      summary: {
        totalMeetings: '会議数',
        totalMeetingsDetail: 'カレンダー内のすべての会議です。',
        upcomingMeetings: '今後の会議',
        upcomingMeetingsDetail: 'まだ完了またはキャンセルされていない会議です。',
        completedMeetings: '完了した会議',
        completedMeetingsDetail: '完了とマークされた会議です。',
        totalMeetingHours: '会議合計時間',
        totalMeetingHoursDetail: '選択期間の会議時間の合計です。',
      },
      weekView: '週表示',
      dayView: '日表示',
      agenda: '議題',
      searchPlaceholder: '会議を検索',
      allStatuses: 'すべてのステータス',
      date: '日付',
      duration: '時間',
      calendar: 'カレンダー',
      meetingSchedule: '会議スケジュール',
      loading: '会議を読み込み中…',
      noMeetings: '選択日には会議がありません。',
      reviewHistory: '履歴を確認',
      historyTitle: '過去・現在・今後',
      worklogLinkage: 'ワークログ連携',
      worklogLinkageDescription: '会議はワークログ項目に紐づけられ、その日の会議時間として自動的に反映されます。',
      findMeetings: '会議を検索',
      filters: 'フィルター',
      statusAndRecurrence: 'ステータスと繰り返し',
      sorting: '並び順',
      dateOrDuration: '日付または時間で並べる',
      history: '履歴',
      auditReady: '監査対応ビュー',
      open: '開く',
      edit: '編集',
      search: '検索',
      defaultProject: '一般',
      defaultParticipants: 'チーム',
      untitledMeeting: '無題の会議',
      oneTime: '一度きり',
      pending: '保留',
      noMeetingDetails: '会議の詳細はありません。',
      reminderTitle: '{minutes}分前リマインダー: {title}',
      reschedulePrompt: '会議を次の日付に変更しますか？（YYYY-MM-DD）',
      details: '詳細',
      agendaLabel: '議題',
      notesLabel: 'メモ',
      actionItems: 'アクション項目',
      actionDone: '完了',
      actionPending: '保留',
      dueBy: '期限',
    },
    calendar: {
      pageTitle: 'カレンダーモジュール',
      pageDescription: '日付を選択して、その日の保存済みワークログや祝日情報を確認します。',
      japaneseCalendar: '日本のカレンダー',
      legend: '凡例',
      selectedDate: '選択日',
      holiday: '祝日',
      currentDate: '今日',
      dayDetails: '日詳細',
      selectedDateLabel: '選択日：',
      holidayMessage: 'この日は祝日としてマークされています：',
      noSavedWorklog: 'この日付には保存済みワークログがありません。',
      createWorklog: 'ワークログを作成',
      savedWorklog: '保存済みワークログ',
      savedAt: '保存日時：',
      status: '状態',
      executionDetails: '実行詳細',
      plannedItems: '計画項目',
      summary: '要約',
      plannedMinutes: '計画分',
      actualMinutes: '実績分',
      meetingTime: '会議時間',
      completion: '完了状況',
      openWorklogPage: 'ワークログページを開く',
      notAvailable: 'なし',
      notRecorded: '未記録',
      noNotes: 'メモなし',
      noDescription: '説明なし',
      noProject: 'プロジェクトなし',
      untitledItem: '無題の項目',
      item: '項目',
      today: '今日',
      workday: '稼働日',
      sunday: '日',
      saturday: '土',
      weeklyCalendar: '週間カレンダー',
      tapADay: '日をタップ',
      previousWeek: '前の週',
      nextWeek: '次の週',
    },
    modal: {
      meeting: {
        createTitle: '会議を作成',
        editTitle: '会議を編集',
        description: '会議を計画し、プロジェクトのワークログに紐づけます。',
        close: '閉じる',
        title: '件名',
        project: 'プロジェクト',
        date: '日付',
        startTime: '開始時間',
        duration: '時間（分）',
        status: 'ステータス',
        participants: '参加者',
        recurrence: '繰り返し',
        descriptionLabel: '説明',
        agenda: '議題',
        notes: 'メモ',
        cancel: 'キャンセル',
        save: '会議を保存',
      },
      project: {
        createTitle: 'プロジェクトを作成',
        editTitle: 'プロジェクトを編集',
        description: 'スコープ、納期、担当チームを整理します。',
        close: '閉じる',
        projectNumber: 'プロジェクト番号',
        projectNumberPlaceholder: '例：PRJ-1042',
        projectName: 'プロジェクト名',
        client: '顧客',
        descriptionLabel: '説明',
        startDate: '開始日',
        endDate: '終了日',
        budgetHours: '予算時間',
        manager: '担当マネージャー',
        teamMembers: 'チームメンバー',
        status: 'ステータス',
        cancel: 'キャンセル',
        save: 'プロジェクトを保存',
      },
    },
    profile: {
      title: 'プロフィール',
      heading: 'ワークログプロフィール用の社員情報とアカウント情報です。編集可能な個人情報と、会社管理の情報を確認できます。',
      saveButton: 'プロフィールを保存',
      editButton: 'プロフィールを編集',
      cancelButton: 'キャンセル',
      welcome: 'ようこそ！',
      completeTitle: 'プロフィールを完了',
      completeDescription: 'プロフィールの情報が不足しています。役職・電話番号・場所・マネージャーを追加して、コラボレーションと通知機能を有効にしましょう。',
      onboardingDescription: '登録ありがとうございます。チームから見つけてもらえるよう、プロフィール詳細を完了してください。',
      personalInfoTitle: '個人情報',
      personalInfoDescription: '編集可能な項目は、同僚があなたを見つけやすくするための情報です。',
      fullName: '氏名',
      email: 'メール',
      employeeId: '社員ID',
      jobTitle: '役職',
      department: '部署',
      accountStatus: 'アカウント状態',
      phone: '電話番号',
      location: '場所',
      manager: 'マネージャー',
      placeholder: '未設定',
      notAssigned: '未割り当て',
      success: 'プロフィールを更新しました。',
      saveError: 'プロフィールを保存できませんでした。',
      blankName: '氏名を入力してください。',
      noRecentActivity: '最近の活動なし',
      active: '有効',
      inactive: '無効',
      pending: '保留',
      employmentTitle: '在籍情報',
      employmentDescription: '会社が管理する情報は読み取り専用です。内容は人事にご確認ください。',
      joiningDate: '入社日',
      role: '役割',
      defaultRole: '従業員',
      accountSettingsTitle: 'アカウント設定',
      accountSettingsDescription: '認証情報、ログイン詳細、社内アクセス権限を管理します。',
      editableFields: '編集可能：氏名、メール、社員ID、部署、役職、電話番号、場所、マネージャー',
      accessLevel: 'アクセス権限',
      defaultAccessLevel: '標準ユーザー',
      lastLogin: '最終ログイン',
      profileVisibility: 'プロフィール公開範囲',
      defaultVisibility: '社内のみ',
      placeholders: {
        fullName: '氏名',
        email: 'メールアドレス',
        employeeId: '社員ID',
        phone: '電話番号',
        location: '勤務地',
        department: '部署',
        manager: 'マネージャー名',
        jobTitle: '役職',
      },
    },
  },
};

const LanguageContext = createContext(null);

const isPlainObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);

// Any key the active language has not translated yet falls back to the English
// value, so a missing entry renders English text instead of crashing the page.
const withFallback = (base, override) => {
  const merged = { ...base };
  Object.entries(override || {}).forEach(([key, value]) => {
    merged[key] = isPlainObject(value) && isPlainObject(base?.[key]) ? withFallback(base[key], value) : value;
  });
  return merged;
};

// Fills {placeholder} tokens in a translated string: format(s.entries, { count: 4 })
export const format = (template, values = {}) =>
  String(template ?? '').replace(/\{(\w+)\}/g, (match, key) => (key in values ? String(values[key]) : match));

const getStoredLanguage = () => {
  if (typeof window === 'undefined') return defaultLanguage;
  const stored = window.localStorage.getItem('workpulse-language');
  return stored && translations[stored] ? stored : defaultLanguage;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getStoredLanguage);
  const locale = language === 'Japanese' ? 'ja-JP' : 'en-US';

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem('workpulse-language', language);
    document.documentElement.lang = language === 'Japanese' ? 'ja' : 'en';
  }, [language]);

  const strings = useMemo(
    () => withFallback(translations[defaultLanguage], translations[language]),
    [language],
  );

  const value = useMemo(
    () => ({ language, setLanguage, locale, languageOptions, strings, format }),
    [language, locale, strings],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
